### ISSUE TITLE
Got error

### ISSUE THREAD

**Issue by obtim** [ntschopp/nba-analyzer#1]
Got this error:
Traceback (most recent call last):
  at block 3, line 49
  at block 3, line 16, in get_player_info()
TypeError: strptime() argument 1 must be str, not float

Why?

**Comment by ntschopp** [comment]
The issue is that nba-reference doesn't have personal information for Craig Sword of the Washington Wizards. The resulting TypeError is due to the code editor trying to run his NaN birth date, which is considered a float datatype rather than a string.
Gotta love all of these covid-related 10-day contracts!
I'll post a bug fix shortly.
